ITEM_ORDER = {
    "Getting Started": [
        "getting-started",
        "installing-anylog",
        "install-ova",
        "anylog-as-service",
        "deployment-scripts",
    ],
    "CLI": [
        "AnyLog-CLI",
        "node-status",
        "get-cmds",
    ],
    "Network & Services": [
        "background-services",
        "network-configurations",
        "node-architecture.md",
        "using-rest",
        "messaging-services",
        "blockchain",
        "policies-metadata",
    ],
    "Managing Data (Southbound)": [
        "southbound-overview",
        "data-ingestion",
        "mapping-policies",
        "UNS",
        "UNS-custom",
        "opcua",
        "using-kafka",
        "telegraf",
        "etherip",
        "grpc",
        "node-red",
        "node-monitoring",
        "syslog",
        "video-streaming",
        "live-data-generator",
        "edgex",
    ],
    "Querying Data (Northbound)": [
        "northbound-overview",
        "queries",
        "sql-setup",
        "grafana",
        "import-grafana-dashboard",
        "PowerBI",
        "Qlik",
        "Google",
        "postgres-connector",
        "notification",
    ],
    "Monitoring & Operations": [
        "node-monitoring",
        "aggregations",
        "high-availability",
    ],
    "Tools & UI": [
        "mcp",
        "remote-gui",
    ],
    "Version Control": [
        "SCRIPTS-CHANGELOGS",
        "DEPLOYMENT_SCRIPTS-CHANGELOGS",
        "DOCKER_COMPOSE-CHANGELOG"
    ],
    "Reference": [
        "FAQ",
        "troubleshooting"
    ],
}