"""
Fetches CHANGELOG.md from the pre-develop branch of each source repo
and writes them into _docs/Version-Control/ in the docs repo.

Triggered by sync-changelogs.yml (schedule, manual, or repository_dispatch).
Requires GH_TOKEN env var set to the shared PAT or GitHub App token.
"""

import os
import sys
import json
import base64
import urllib.request
import urllib.error
from pathlib import Path

ROOT_PATH = os.path.dirname(__file__).split(".github")[0]

SOURCES = [
    {
        "repo":   "AnyLog-co/AnyLog-Network",
        "branch": "pre-develop",
        "file":   "CHANGELOG.md",
        "dest":   f"{ROOT_PATH}/_docs/Version-Control/SOURCE-CHANGELOGS.md",
    },
    {
        "repo":   "AnyLog-co/docker-compose",
        "branch": "pre-develop",
        "file":   "CHANGELOG.md",
        "dest":   f"{ROOT_PATH}/_docs/Version-Control/DOCKER_COMPOSE-CHANGELOG.md",
    },
    {
        "repo":   "AnyLog-co/deployment-scripts",
        "branch": "pre-develop",
        "file":   "CHANGELOG.md",
        "dest":   f"{ROOT_PATH}/_docs/Version-Control/DEPLOYMENT_SCRIPTS-CHANGELOGS.md",
    },
]

GITHUB_API = "https://api.github.com"


def fetch_file(repo: str, branch: str, filepath: str, token: str) -> str | None:
    url = f"{GITHUB_API}/repos/{repo}/contents/{filepath}?ref={branch}"
    req = urllib.request.Request(url, headers={
        "Accept":               "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Authorization":        f"Bearer {token}",
    })
    try:
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read())
    except urllib.error.HTTPError as exc:
        print(f"  ✗ HTTP {exc.code} — {repo}/{filepath}@{branch}: {exc.reason}")
        return None

    if data.get("encoding") == "base64":
        return base64.b64decode(data["content"]).decode("utf-8")
    return data.get("content")


def ensure_front_matter(content: str, source: dict) -> str:
    """Prepend Jekyll front matter if the upstream file doesn't already have it."""
    if content.lstrip().startswith("---"):
        return content

    title = Path(source["dest"]).stem.replace("-", " ").replace("_", " ").title()
    header = (
        f"---\n"
        f"title: {title}\n"
        f"description: Auto-synced from {source['repo']} "
        f"(branch: {source['branch']})\n"
        f"layout: page\n"
        f"---\n\n"
        f"<!-- AUTO-GENERATED — do not edit this file directly -->\n"
        f"<!-- Source: https://github.com/{source['repo']}/blob/"
        f"{source['branch']}/{source['file']} -->\n\n"
    )
    return header + content


def main():
    token = os.environ.get("GH_TOKEN", "")
    if not token:
        print("✗ GH_TOKEN is not set")
        sys.exit(1)

    errors = []
    for src in SOURCES:
        print(f"→ {src['repo']} ({src['branch']}/{src['file']}) …")
        content = fetch_file(src["repo"], src["branch"], src["file"], token)

        if content is None:
            errors.append(src["repo"])
            continue

        content = ensure_front_matter(content, src)
        dest = Path(src["dest"])
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        print(f"  ✓ {dest}  ({len(content):,} bytes)")

    if errors:
        print(f"\n✗ Failed: {', '.join(errors)}")
        sys.exit(1)

    print("\n✓ Done.")


if __name__ == "__main__":
    main()