services:
  docs:
    build: .
    container_name: anylog-docs
    user: root
    ports:
      - "4000:4000"
      - "35729:35729"
    command: bash /srv/content/.github/scripts/dev-start.sh
    environment:
      - ANYLOG_DOCS_SOURCE_DIR=/srv/documentation
    volumes:
      - ${LOCAL_DOCS:-.}:/srv/documentation:cached
      - .:/srv/content:cached
      - bundle-cache:/srv/bundle

volumes:
  bundle-cache: